# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - nkduy
  run: |
    for i in {1..3}; do
      if npx azure-webapps-deploy --app-name nkduy --slot-name Production; then
        break
      else
        echo "Deploy failed, retrying in 30 seconds..."
        sleep 30
      fi
    done
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: "my-app"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./release.zip"
  AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A0279718C2A4C00A54C03CB7BEA4133 }}
  AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_EBC3F7F2719348429166D6D57A4F6D04 }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31EF0A95B99C4FB896B1D90F85CF296A }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A0279718C2A4C00A54C03CB7BEA4133 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EBC3F7F2719348429166D6D57A4F6D04 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31EF0A95B99C4FB896B1D90F85CF296A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'nkduy'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          retry:
            max-attempts: 3
            delay-seconds: 30