jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_... }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_... }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_... }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'khanhsduy'
        slot-name: 'Production'
        package: .
