name: Build and deploy Python app to Azure Web App - khanhsduy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Optional: Run tests here if needed

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C50C5C76F3EB424F9039D34FB4E29C45 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E6E6CE074E74BBBB24656144C75C3A8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A58B2AE8D25B4E1B93CEE31C1006513A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'khanhsduy'
          slot-name: 'Production'
          package: .